name: Deploy to GitHub Pages

# 触发条件: 当 docs 分支有推送时运行
on:
  push:
    branches:
      - main  # 监听 main 分支的推送

# 权限配置
permissions:
  contents: write  # 允许写入 gh-pages 分支

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整的历史记录

      # Step 2: 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'  # 使用 npm 缓存

      # Step 3: 安装依赖
      - name: Install dependencies
        run: npm install 

      # Step 4: 清除旧的 actions 缓存
      - name: Clear old actions cache
        run: sudo rm -rf ${{ github.workspace }}/_actions/JamesIves/github-pages-deploy-action

      - name: Grant execute permission for vuepress
        run: chmod +x node_modules/.bin/vuepress
      
      - name: Build VuePress
        run: npm run build

      # 部署到 GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist

